version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/djthorpe/rotel
    steps:
      - checkout
      - run: make test
      - run: make install
      - run: make clean
